import type { Theme } from '@/types'

export const cobaltTheme: Theme = {
  base: {
    '--md-primary-color': `#fc851e`,
    'font-family': `AvenirNext-Regular, -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji`,
    'font-size': `1rem`,
    'color': `#dbf0ef`,
    'background-color': `#142738`,
    'line-height': `1.6em`,
    '-webkit-text-size-adjust': `100%`,
    '-webkit-font-smoothing': `antialiased`,
    'text-rendering': `optimizeLegibility`,
    '-moz-box-sizing': `border-box`,
    '-webkit-box-sizing': `border-box`,
    'box-sizing': `border-box`,
  },
  block: {
    container: {
      width: `100%`,
      margin: `0`,
      padding: `1em`,
    },
    h1: {
      'margin-top': `1.5em`,
      'margin-bottom': `0.75em`,
      'margin-left': `0`,
      'margin-right': `0`,
      'font-family': `AvenirNext-Medium`,
      'font-weight': `500`,
      'line-height': `1.5em`,
      'color': `#d3c845`,
      'font-size': `1.5em`,
      'text-align': `center`,
    },
    h2: {
      'margin-top': `1.5em`,
      'margin-bottom': `0.75em`,
      'margin-left': `0`,
      'margin-right': `0`,
      'font-family': `AvenirNext-Medium`,
      'font-weight': `500`,
      'line-height': `1.5em`,
      'color': `#d3c845`,
      'font-size': `1.3em`,
    },
    h3: {
      'margin-top': `1.5em`,
      'margin-bottom': `0.75em`,
      'margin-left': `0`,
      'margin-right': `0`,
      'font-family': `AvenirNext-Medium`,
      'font-weight': `500`,
      'line-height': `1.5em`,
      'color': `#d3c845`,
      'font-size': `1.1em`,
    },
    h4: {
      'margin-top': `1.5em`,
      'margin-bottom': `0.75em`,
      'margin-left': `0`,
      'margin-right': `0`,
      'font-family': `AvenirNext-Medium`,
      'font-weight': `500`,
      'line-height': `1.5em`,
      'color': `#d3c845`,
      'font-size': `1em`,
    },
    h5: {
      'margin-top': `1.5em`,
      'margin-bottom': `0.75em`,
      'margin-left': `0`,
      'margin-right': `0`,
      'font-family': `AvenirNext-Medium`,
      'font-weight': `500`,
      'line-height': `1.5em`,
      'color': `#d3c845`,
      'font-size': `1em`,
    },
    h6: {
      'margin-top': `1.5em`,
      'margin-bottom': `0.75em`,
      'margin-left': `0`,
      'margin-right': `0`,
      'font-family': `AvenirNext-Medium`,
      'font-weight': `500`,
      'line-height': `1.5em`,
      'color': `#d3c845`,
      'font-size': `1em`,
    },
    p: {
      'margin': `0.75em 0 0.45em`,
      'margin-left': `0`,
      'margin-right': `0`,
    },
    blockquote: {
      'display': `block`,
      'padding-left': `0.8em`,
      'border-left': `0.2em solid #fc851e`,
      'margin': `0.75em 0 0.45em`,
    },
    blockquote_p: {
      'margin-top': `0`,
      'margin-bottom': `0`,
    },
    code_pre: {
      'padding': `0.7em 1em`,
      'border': `solid 1px #102432`,
      'font-size': `0.9em`,
      'overflow-x': `auto`,
      'margin': `0.75em 0 0.45em`,
      'background-color': `#152d3e`,
      'color': `#dbf0ef`,
      'font-family': `Menlo-Regular, Menlo, Monaco, Consolas, "Courier New", monospace`,
      'line-height': `1.5rem`,
      'white-space': `pre`,
      'word-spacing': `normal`,
      'word-break': `normal`,
      'word-wrap': `normal`,
      '-moz-tab-size': `4`,
      '-o-tab-size': `4`,
      'tab-size': `4`,
      '-webkit-hyphens': `none`,
      '-moz-hyphens': `none`,
      '-ms-hyphens': `none`,
      'hyphens': `none`,
    },
    code: {
      'display': `inline`,
      'border': `solid 1px #102432`,
      'padding': `0.2em 0.5em`,
      'font-size': `0.9em`,
      'color': `#e1eff3`,
      'background-color': `#152d3e`,
      'font-family': `Menlo-Regular, Menlo, Monaco, Consolas, "Courier New", monospace`,
    },
    image: {
      'max-width': `100%`,
      'height': `auto`,
    },
    ol: {
      'list-style': `none`,
      'display': `flex`,
      'flex-direction': `column`,
      'counter-reset': `list-counter`,
      'margin': `0.75em 0 0.45em`,
      'margin-left': `-1.7em`,
    },
    ul: {
      'list-style': `none`,
      'display': `flex`,
      'flex-direction': `column`,
      'margin': `0em 0 0em`,
      'margin-left': `-1.7em`,
    },
    hr: {
      'margin': `0.75em auto`,
      'height': `1px`,
      'border': `0`,
      'background-color': `#102432`,
      'border-style': `inset`,
      'border-width': `1px`,
    },
    footnotes: {},
    figure: {
      margin: `0.75em 0 0.45em`,
    },
    block_katex: {},
    blockquote_note: {},
    blockquote_tip: {},
    blockquote_info: {},
    blockquote_important: {},
    blockquote_warning: {},
    blockquote_caution: {},
    blockquote_title: {},
    blockquote_title_note: {},
    blockquote_title_tip: {},
    blockquote_title_info: {},
    blockquote_title_important: {},
    blockquote_title_warning: {},
    blockquote_title_caution: {},
    blockquote_p_note: {},
    blockquote_p_tip: {},
    blockquote_p_info: {},
    blockquote_p_important: {},
    blockquote_p_warning: {},
    blockquote_p_caution: {},
  },
  inline: {
    listitem: {
      'display': `flex`,
      'align-items': `flex-start`,
      'margin': `0.2em 8px`,
      'padding': `0`,
    },

    listitem_marker: {
      'width': `2em`,
      'text-align': `right`,
      'margin-right': `0.5em`,
      'flex-shrink': `0`,
    },

    listitem_content: {
      flex: `1`,
    },
    codespan: {
      'display': `inline`,
      'border': `solid 1px #102432`,
      'padding': `0.2em 0.5em`,
      'font-size': `0.9em`,
      'color': `#e1eff3`,
      'background-color': `#152d3e`,
      'font-family': `Menlo-Regular, Menlo, Monaco, Consolas, "Courier New", monospace`,
    },
    link: {
      'color': `#36c99b`,
      'text-decoration': `none`,
    },
    wx_link: {
      'color': `#36c99b`,
      'text-decoration': `none`,
    },
    strong: {
      'font-weight': `bold`,
    },
    em: {
      'font-style': `italic`,
    },
    table: {
      'color': `#e1eff3`,
      'border-collapse': `collapse`,
      'background-color': `#152d3e`,
      'border-spacing': `0`,
      'font-size': `1em`,
      'border': `1px solid #102432`,
    },
    thead: {
      'text-align': `left`,
      'font-weight': `normal`,
      'vertical-align': `middle`,
    },
    td: {
      'padding': `0.7em 1em`,
      'font-size': `0.9em`,
      'border': `1px solid #102432`,
      'text-align': `left`,
      'font-weight': `normal`,
      'vertical-align': `middle`,
    },
    footnote: {},
    figcaption: {
      'text-align': `center`,
    },
    inline_katex: {},
  },
}
